#!/usr/bin/with-contenv bash

# create folders
mkdir -p "$APP_ROOT"
mkdir -p "$CONFIG"
#maybe should do /mnt and newgroup /folders, but too tired

# install app
if [[ -d "$APP_ROOT/$APPDIRNAME/.git" ]]
then
    cd "$APP_ROOT/$APPDIRNAME"
    git stash
    git checkout $GITBRANCH
    git pull
else
    git clone $GITURL "$APP_ROOT/$APPDIRNAME" -b $GITBRANCH
fi

# permissions
chown -R abc:abc "$APP_ROOT"
chown -R abc:abc "$CONFIG"
