#!/usr/bin/with-contenv bash

#update hydra version
new_hydra_ver=$(curl -sX GET "https://api.github.com/repos/theotherp/nzbhydra2/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]')
new_hydra_ver=${new_hydra_ver#v}
current_hydra_ver=$(find /tmp/hydra -iname core-*.jar | grep -o '[0-9]\.[0-9]\.[0-9]')
#current_hydra_ver=$(java -jar -DfromWrapper "${APP_ROOT}/${APPDIRNAME}/lib/core-2.3.1-exec.jar" --version | awk '{print $NF}')
current_hydra_ver=${current_hydra_ver#v}
echo "Current Hydra Version: [${current_hydra_ver}]"
echo "New Hydra Version: [${new_hydra_ver}]"

# create folders
mkdir -p "${APP_ROOT}"
mkdir -p "${CONFIG}"
#maybe should do /mnt and newgroup /folders, but too tired

if [ "${current_hydra_ver}" != "${new_hydra_ver}" ]
then
    echo "*****Updating HYDRA from version [${current_hydra_ver}]->[${new_hydra_ver}]******"
    #HYDRA_VER="${new_hydra_ver}"
    # if old app still around, scrap it
    if [[ -d "${APP_ROOT}/${APPDIRNAME}" ]]
    then
        rm -rf "${APP_ROOT}/${APPDIRNAME}"
        mkdir "${APP_ROOT}/${APPDIRNAME}"
    fi

    curl -o "/tmp/nzbhydra2.zip" -L "https://github.com/theotherp/nzbhydra2/releases/download/v${new_hydra_ver}/nzbhydra2-${new_hydra_ver}-linux.zip"
#    git stash
#    git checkout ${GITBRANCH}
#    git pull
    unzip "/tmp/nzbhydra2.zip" -d "${APP_ROOT}/${APPDIRNAME}"
    curl -o "${APP_ROOT}/${APPDIRNAME}/nzbhydra2wrapper.py" -L  "https://raw.githubusercontent.com/theotherp/nzbhydra2/master/other/wrapper/nzbhydra2wrapper.py"
    chmod +x "${APP_ROOT}/${APPDIRNAME}/nzbhydra2wrapper.py"
fi

# permissions
chown -R abc:abc "${APP_ROOT}"
chown -R abc:abc "${CONFIG}"
