#!/usr/bin/with-contenv bash

#Probs should be setting these as ENV in the Dockerfile
if [ -z "${CONFIG}" ]
then
    CONFIG=/config
fi

if [ -z "${APP_ROOT}" ]
then
    APP_ROOT=/app
fi

if [ -z "${APPDIRNAME}" ]
then
    APPDIRNAME=hydra
fi

if [ -z "${GITURL}" ]
then
    GITURL=https://github.com/theotherp/nzbhydra.git
fi

if [ -z "${GITBRANCH}" ]
then
    GITBRANCH=master
fi

if [ -z "${APP_EXEC}" ]
then
    APP_EXEC=nzbhydra.py
fi

if [ -z "${APP_OPTS}" ]
then
    APP_OPTS="--nobrowser --config=${CONFIG}/settings.cfg --database=${CONFIG}/nzbhydra.db --logfile=${CONFIG}/nzbhydra.log"
fi

if [ -z "${APP_COMP}" ]
then
    APP_COMP="python"
fi

####ALL user vars set up and checked now, I think.....

# create folders
mkdir -p "$APP_ROOT"
mkdir -p "$CONFIG"
#maybe should do /mnt and newgroup /folders, but too tired

# install app
if [[ -d "$APP_ROOT/$APPDIRNAME/.git" ]]
then
    cd "$APP_ROOT/$APPDIRNAME"
    git stash
    git checkout $GITBRANCH
    git pull
else
    git clone $GITURL "$APP_ROOT/$APPDIRNAME" -b $GITBRANCH
fi

# permissions
chown -R abc:abc "$APP_ROOT"
chown -R abc:abc "$CONFIG"
